services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-paag-challenge-app
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ".:/var/www"
    networks:
      - sail
    depends_on:
      - pgsql
      - pgbouncer

  pgsql:
    container_name: api-paag-challenge-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth=md5
    ports:
      - "5432:5432"
    volumes:
      - "saildatabase:/var/lib/postgresql/data"
    networks:
      - sail

  pgbouncer:
    container_name: api-paag-challenge-pgbouncer
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      ADMIN_USERS: postgres,admin
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini"
      - "./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt"
    networks:
      - sail
    depends_on:
      - pgsql

networks:
  sail:
    driver: bridge

volumes:
  saildatabase:
    driver: local
